"use strict";Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});function h(n,t){return t?typeof t=="function"?t(n):`${t}${encodeURIComponent(n)}`:n}const w={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"',"&#39;":"'","&apos;":"'"},p=/&(?:amp|lt|gt|quot|#39|apos);/g;function f(n){return n.replace(p,t=>w[t]??t)}function T(n,t){const e=[/<link[^>]+rel=["']apple-touch-icon["'][^>]+href=["']([^"']+)["']/i,/<link[^>]+rel=["']icon["'][^>]+type=["']image\/png["'][^>]+href=["']([^"']+)["']/i,/<link[^>]+rel=["']icon["'][^>]+href=["']([^"']+)["']/i];for(const i of e){const c=n.match(i);if(c){const o=c[1];if(/^https?:\/\//.test(o))return o;const a=new URL(t);return new URL(o,a).href}}}function H(n){const t=n.match(/<title[^>]*>([^<]+)<\/title>/i);return t?f(t[1].trim()):void 0}function g(n,t){const e=o=>{const a=new RegExp(`<meta[^>]+property=["']og:${o}["'][^>]+content=["']([^"']+)["']`,"i"),r=n.match(a);if(r)return f(r[1]);const s=new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:${o}["']`,"i"),l=n.match(s);return l?f(l[1]):void 0},i=e("title")??H(n),c=e("image")??(t?T(n,t):void 0);return{title:i,description:e("description"),image:c,siteName:e("site_name"),url:e("url")}}async function E(n,t){const e=await fetch(h(n,t));return g(await e.text(),n)}const G=[/^Contribute to .+ on GitHub\.?$/i,/\.?\s*Contribute to .+ on GitHub\.?$/i,/^GitHub - [^:]+: /,/ - [A-Za-z0-9-]+\/[A-Za-z0-9._-]+$/],R=/^GitHub - /;function m(n){let t=n.trim();for(const e of G)e.test(t)&&(t=t.replace(e,""));return t.trim()}function b(n,t){var c;let e=n.replace(R,"");const i=t.match(/github\.com\/([^/]+)\/([^/]+)/);if(i){const o=`${i[1]}/${i[2]}`,a=new RegExp(`^${i[1].replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}/[^:]+:\\s*`);if(e.startsWith(`${o}: `))e=i[2];else if(e===o)e=i[2];else if(a.test(e)){const r=(c=e.match(/^[^/]+\/([^:]+)/))==null?void 0:c[1];r&&(e=r)}}return e.trim()}function u(n){return n.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}function d(n,t,e){const i=(e==null?void 0:e.width)??400,c=(e==null?void 0:e.showTitle)??!0,o=(e==null?void 0:e.showDesc)??!0,a=(e==null?void 0:e.cleanGitHub)??!0;let r=t.title??"",s=t.description??"";a&&/github\.com/.test(n)&&(r&&(r=b(r,n)),s&&(s=m(s)));const l=[];t.image&&l.push(`<img src="${u(t.image)}" alt="${u(r)}" width="${i}">`),c&&r&&l.push(`<br><b>${u(r)}</b>`),o&&s&&l.push(`<br><sub>${u(s)}</sub>`);const $=l.join(`
`);return`<td width="${i}" valign="top">
<a href="${u(n)}">
${$}
</a>
</td>`}function C(n,t){return`<table><tr>
${n.map(i=>d(i.url,i.meta,t)).join(`
`)}
</tr></table>`}function v(n,t){const e=(t==null?void 0:t.cols)??2,i=[];for(let c=0;c<n.length;c+=e){const a=n.slice(c,c+e).map(r=>d(r.url,r.meta,t));i.push(`<tr>
${a.join(`
`)}
</tr>`)}return`<table>
${i.join(`
`)}
</table>`}exports.cleanGitHubDescription=m;exports.cleanGitHubTitle=b;exports.decodeHtmlEntities=f;exports.fetchOgMeta=E;exports.parseOgTags=g;exports.renderCard=d;exports.renderCardGrid=v;exports.renderCardRow=C;exports.resolveProxy=h;
